#!/bin/sh

# Change this to your getmail directory; defaults to /usr/lib/getmail
GETMAILPATH="/usr/lib/getmail"

PYTHONPATH="${GETMAILPATH}:${PYTHONPATH}"

# You can change this to point to your Python interpreter if you wish.
PYTHON=`which python`

exec "$PYTHON" ${GETMAILPATH}/getmail.py $@
