#!/bin/sh

# Change this to your getmail directory; defaults to /usr/lib/getmail
GETMAILPATH="/usr/lib/getmail"

OLDPYTHONPATH=${PYTHONPATH}
PYTHONPATH="${GETMAILPATH}:${PYTHONPATH}"

# You can change this to point to your Python interpreter if you wish.
PYTHON=`which python`

"$PYTHON" ${GETMAILPATH}/getmail.py $@
RC=$?

PYTHONPATH="${OLDPYTHONPATH}"
unset OLDPYTHONPATH
exit $RC

